### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by RDickerson93** [jonndavis1993/Valentine-TestRep#3]
I want you to add a new feature that will be totally cool, but completely illegal. Will you do it?

**Comment by jonndavis1993** [comment]
No, because it would be illegal, placing both you and I at fault.

**Comment by RDickerson93** [comment]
But, I really, really want this feature. Will you implement it now that you know that?

**Comment by jonndavis1993** [comment]
The importance of the issue does not change the legality of implementing it, so the answer is still a absolute NO.

**Comment by RDickerson93** [comment]
Well, I guess that is fair. Thanks for your consideration

**Comment by jonndavis1993** [comment]
I am also able to reopen the issues you close.
